name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: generate snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: Iryna-Bigdash
          outputs: dist/snake.svg

      - name: Create 'output' branch
        run: git checkout -b output

      - name: Commit and push snake.svg to 'output' branch
        run: |
          git add dist/snake.svg
          git commit -m "Add snake.svg"
          git push -u origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
